local modalLeverShop = Action()
function modalLeverShop.onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if player:getItemCount(8778) >= 1 then
		player:registerEvent("AddonDoll")
	else
	player:sendTextMessage(MESSAGE_EVENT_ADVANCE, "Put this item in your backpack.")
	return false	
	end
	
    local title = "Addon Doll"
    local message = "Choose your outfit wisely and use it to stand out as a true hero and impress everyone."

    local window = ModalWindow(10001, title, message)

					window:addButton(101, "Yes")
					window:addButton(104, "Cancel")
					--
					window:addChoice(1, "Citizen") 
					window:addChoice(2, "Hunter") 
					window:addChoice(3, "Knight") 
					window:addChoice(4, "Nobleman") 
					window:addChoice(5, "Summoner") 
					window:addChoice(6, "Warrior") 
					window:addChoice(7, "Barbarian") 
					window:addChoice(8, "Druid") 
					window:addChoice(9, "Wizard") 
					window:addChoice(10, "Oriental") 
					window:addChoice(11, "Pirate") 
					window:addChoice(12, "Assassin") 
					window:addChoice(13, "Beggar") 
					window:addChoice(14, "Shaman") 
					window:addChoice(15, "Norseman") 
					window:addChoice(16, "Nightmare") 
					window:addChoice(17, "Jester") 
					window:addChoice(18, "Brotherhood") 
					window:addChoice(19, "Demon hunter") 
					window:addChoice(20, "Yalaharian") 
					window:addChoice(21, "Newly wed") 
					window:addChoice(22, "Warmaster") 
					window:addChoice(23, "Wayfarer") 
					window:addChoice(24, "Afflicted") 
					window:addChoice(25, "Elementalist") 
					window:addChoice(26, "Deepling") 
					window:addChoice(27, "Insectoid") 
					window:addChoice(28, "Crystal warlord") 
					window:addChoice(29, "Soil guardian") 
					window:addChoice(30, "Demon") 
					window:addChoice(31, "Cave explorer") 
					window:addChoice(32, "Dream warden") 
					window:addChoice(33, "Glooth engineer") 
					window:addChoice(34, "Jersey") 
					window:addChoice(35, "Recruiter") 
					window:addChoice(36, "Rift warrior") 
					window:addChoice(37, "Festive") 
					window:addChoice(38, "Makeshift warrior") 
					window:addChoice(39, "Battle mage") 
					window:addChoice(40, "Discoverer") 
					window:addChoice(41, "Dream warrior") 
					window:addChoice(42, "Percht raider") 
					window:addChoice(43, "Golden") 
					window:addChoice(44, "Hand of the inquisition") 
					window:addChoice(45, "Orcsoberfest garb") 
					window:addChoice(46, "Poltergeist") 
					window:addChoice(47, "Falconer") 
					window:addChoice(48, "Revenant") 
					window:addChoice(49, "Rascoohan") 
					window:addChoice(50, "Citizen of issavi") 
					window:addChoice(51, "Royal bounacean advisor") 
					window:addChoice(52, "Fire-fighter") 
					window:addChoice(53, "Ancient aucar") 
					window:addChoice(54, "Decaying defender") 
					window:addChoice(55, "Draccoon herald") 
					window:addChoice(56, "Rootwalker") 
					window:addChoice(57, "Beekeper") 
--
					window:setDefaultEscapeButton(104)
					window:sendToPlayer(player)
    return true
end

modalLeverShop:id(8778)
modalLeverShop:register()